const $=id=>document.getElementById(id);let stations=[],devices=[],view=[],current=null,currentDevice=null,sortKey='sourceNo',sortDir=1,queueDept='All';
const selected={location:new Set(),office:new Set(),businessLine:new Set(),department:new Set(),review:new Set(),deviceType:new Set(),health:new Set(),completion:new Set()};
const defs=[['location','Locations'],['office','Facilities / offices'],['businessLine','Business lines'],['department','Departments'],['review','Audit status'],['deviceType','Device types'],['health','Data health'],['completion','Completion']];
const stationFields=['location','office','floor','suite','businessLine','department','station','expectedSlots','review','auditor','auditDate'];const deviceFields=['afpmgTag','serialNumber','assignedUser','status','manufacturer','model','ipAddress','phoneExt','phoneMac','warrantyStatus','warrantyDate','notes'];
const labels={location:'Location',office:'Facility / Office',floor:'Floor',suite:'Suite',businessLine:'Business Line',department:'Department',station:'Station Name',expectedSlots:'Expected Hardware',review:'Audit Status',auditor:'Auditor',auditDate:'Audit Date',afpmgTag:'AFPMG Tag',serialNumber:'Serial Number',assignedUser:'Assigned User',status:'Device Status',manufacturer:'Manufacturer',model:'Model',ipAddress:'IP Address',phoneExt:'Phone Extension',phoneMac:'Phone MAC',warrantyStatus:'Warranty Status',warrantyDate:'Warranty Date',notes:'Notes'};
const checks=['labelPresent','labelsReplaced','chargersLabeled','printerIpLabeled','phoneExtVerified','phoneMacRecorded','phoneDisplayVerified','devicesAccounted'];
async function init(){try{[stations,devices]=await Promise.all([fetch('data/stations.json').then(r=>r.json()),fetch('data/devices.json').then(r=>r.json())]);const saved=JSON.parse(localStorage.getItem('pmgAuditEdits')||'{}');stations=stations.map(s=>({...s,...saved[s.stationId]}));$('loadState').textContent=`${stations.length} stations loaded`;buildFilterPane();bind();apply()}catch(e){$('loadState').textContent='Data load failed';console.error(e)}}
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));const stationDevices=id=>devices.filter(d=>d.stationId===id);
function valuesFor(type){if(type==='deviceType')return [...new Set(devices.map(d=>d.deviceType))];if(type==='health')return['Missing asset tag','Missing serial','Missing user','Missing IP','Missing phone extension'];if(type==='completion')return['0%','1–25%','26–50%','51–75%','76–100%'];return [...new Set(stations.map(s=>s[type]).filter(Boolean))]}
function countFor(type,val){if(type==='deviceType')return stations.filter(s=>stationDevices(s.stationId).some(d=>d.deviceType===val)).length;if(type==='health')return stations.filter(s=>hasHealth(s,val)).length;if(type==='completion')return stations.filter(s=>completionBand(completion(s))===val).length;return stations.filter(s=>s[type]===val).length}
function buildFilterPane(){$('filterGroups').innerHTML=defs.map(([type,title])=>`<section class="filterGroup"><h3>${title}</h3><div class="filterChoices">${valuesFor(type).sort().map(v=>`<label><input type="checkbox" data-filter="${type}" value="${esc(v)}"> ${esc(v)} <span>${countFor(type,v)}</span></label>`).join('')}</div></section>`).join('');document.querySelectorAll('[data-filter]').forEach(c=>c.onchange=()=>{selected[c.dataset.filter][c.checked?'add':'delete'](c.value);apply()})}
function bind(){$('search').oninput=apply;['clearFilters','clearTop'].forEach(id=>$(id).onclick=clearFilters);$('openFilters').onclick=$('filterButton').onclick=()=>$('filterPane').classList.add('open');$('closeFilters').onclick=()=>$('filterPane').classList.remove('open');document.querySelectorAll('th[data-sort]').forEach(th=>th.onclick=()=>{sortDir=sortKey===th.dataset.sort?-sortDir:1;sortKey=th.dataset.sort;apply()});$('exportBtn').onclick=exportData;$('addBtn').onclick=()=>openAudit();$('closeAudit').onclick=()=>closeAudit();$('queueToggle').onclick=()=>$('queuePane').classList.toggle('open');$('queueSearch').oninput=renderQueue;document.querySelectorAll('.auditNav button').forEach(b=>b.onclick=()=>showPage(b.dataset.section));$('quickPass').onclick=quickPass;$('flagIssue').onclick=flagIssue;$('saveStation').onclick=()=>save(false);$('saveNext').onclick=()=>save(true);$('skipStation').onclick=()=>navigate(1);$('previousStation').onclick=()=>navigate(-1)}
function completion(s){const ds=stationDevices(s.stationId),essential=['location','office','station','department'],done=essential.filter(x=>s[x]).length+ds.filter(d=>d.afpmgTag&&d.serialNumber).length,total=essential.length+ds.length;return total?Math.round(done/total*100):0}function completionBand(n){return n===0?'0%':n<=25?'1–25%':n<=50?'26–50%':n<=75?'51–75%':'76–100%'}
function missingList(s){const d=stationDevices(s.stationId),a=[];if(!s.auditor)a.push('Auditor');if(!s.auditDate)a.push('Audit date');if(d.some(x=>!x.afpmgTag))a.push('Asset tag');if(d.some(x=>!x.serialNumber))a.push('Serial');if(d.some(x=>!x.assignedUser))a.push('User');return a}function hasHealth(s,v){const d=stationDevices(s.stationId);return v==='Missing asset tag'?d.some(x=>!x.afpmgTag):v==='Missing serial'?d.some(x=>!x.serialNumber):v==='Missing user'?d.some(x=>!x.assignedUser):v==='Missing IP'?d.some(x=>!x.ipAddress&&['Desktop','Laptop','Printer'].includes(x.deviceType)):d.some(x=>x.deviceType==='Phone'&&!x.phoneExt)}
function matchSet(type,s){const set=selected[type];if(!set.size)return true;if(type==='deviceType')return[...set].some(v=>stationDevices(s.stationId).some(d=>d.deviceType===v));if(type==='health')return[...set].some(v=>hasHealth(s,v));if(type==='completion')return set.has(completionBand(completion(s)));return set.has(s[type])}
function apply(){const q=$('search').value.toLowerCase();view=stations.filter(s=>{const text=[...Object.values(s),...stationDevices(s.stationId).flatMap(Object.values)].join(' ').toLowerCase();return(!q||text.includes(q))&&defs.every(([t])=>matchSet(t,s))});view.sort((a,b)=>{const av=sortKey==='completion'?completion(a):sortKey==='missing'?missingList(a).length:a[sortKey],bv=sortKey==='completion'?completion(b):sortKey==='missing'?missingList(b).length:b[sortKey];return String(av??'').localeCompare(String(bv??''),undefined,{numeric:true})*sortDir});render()}
function render(){document.querySelectorAll('th').forEach(x=>x.classList.toggle('sorted',x.dataset.sort===sortKey));$('sortNote').textContent=`Sorted by ${labels[sortKey]||sortKey} ${sortDir>0?'ascending':'descending'}`;$('resultCount').textContent=`Showing ${view.length} of ${stations.length} stations`;$('activeFilterCount').textContent=activeCount()?`${activeCount()} filter choices selected`:'No filters selected';$('kStations').textContent=stations.length;$('kDevices').textContent=devices.length;$('kReview').textContent=stations.filter(s=>s.review!=='Verified').length;$('kLocations').textContent=new Set(stations.map(s=>s.location)).size;$('rows').innerHTML=view.map(rowHTML).join('');$('cards').innerHTML=view.map(cardHTML).join('')}
function rowHTML(s){const c=completion(s),m=missingList(s);return`<tr onclick="openAudit('${s.stationId}')"><td><b>${esc(s.station)}</b></td><td>${esc(s.stationId)}</td><td>${esc(s.location)}</td><td>${esc(s.office)}</td><td>${esc(s.floor)}</td><td>${esc(s.businessLine)}</td><td>${esc(s.department)}</td><td><div class="bar"><i style="width:${c}%"></i></div>${c}%</td><td>${m.slice(0,2).map(x=>`<span class="badge amber">${x}</span>`).join(' ')||'<span class="badge green">Complete</span>'}</td><td><span class="badge ${s.review==='Verified'?'green':'amber'}">${esc(s.review)}</span></td><td><button onclick="event.stopPropagation();openAudit('${s.stationId}')">Inspect</button></td></tr>`}
function cardHTML(s){return`<button class="stationCard" onclick="openAudit('${s.stationId}')"><small>${esc(s.stationId)}</small><h3>${esc(s.station)}</h3><div>${esc(s.location)} · ${esc(s.office)} · ${esc(s.department)}</div><div class="bar"><i style="width:${completion(s)}%"></i></div><small>${completion(s)}% complete · ${missingList(s).length} missing categories</small></button>`}
function activeCount(){return Object.values(selected).reduce((n,s)=>n+s.size,0)}function clearFilters(){Object.values(selected).forEach(s=>s.clear());document.querySelectorAll('[data-filter]').forEach(c=>c.checked=false);$('search').value='';apply();toast('All filters cleared')}
function openAudit(id){current=stations.find(s=>s.stationId===id)||{stationId:'NEW-'+Date.now(),station:'New Station',review:'Needs Review'};currentDevice=null;renderAudit();$('audit').showModal()}
function renderAudit(){$('auditName').textContent=current.station;$('auditId').textContent=current.stationId;renderCrumbs();renderSummary();renderStationFields();renderAttention();renderDevices();renderChecks();renderQueueFilters();renderQueue();showPage('overview')}
function renderCrumbs(){const items=[['location',current.location],['office',current.office],['businessLine',current.businessLine],['department',current.department]];$('crumbs').innerHTML=items.filter(x=>x[1]).map(([k,v])=>`<button class="crumb ${selected[k]?.has(v)?'active':''}" onclick="toggleCrumb('${k}','${esc(v)}')">${esc(v)}</button>`).join('')}
function toggleCrumb(k,v){if(!selected[k])return;selected[k].has(v)?selected[k].delete(v):selected[k].add(v);document.querySelectorAll(`[data-filter="${k}"]`).forEach(c=>c.checked=selected[k].has(c.value));apply();renderCrumbs();renderQueue();toast(`${v} queue filter ${selected[k].has(v)?'applied':'removed'}`)}
function renderSummary(){const c=completion(current),ds=stationDevices(current.stationId),miss=missingList(current);$('stationProgress').style.width=c+'%';$('stationProgressText').textContent=c+'% complete';$('summaryStats').className='summaryStats';$('summaryStats').innerHTML=`<div class="stat"><small>Devices</small><b>${ds.filter(d=>d.afpmgTag).length}/${ds.length} identified</b></div><div class="stat"><small>Missing</small><b>${miss.length} categories</b></div><div class="stat"><small>Status</small><b>${esc(current.review)}</b></div>`}
function renderStationFields(){$('stationFields').innerHTML=stationFields.map(f=>`<label>${labels[f]}${f==='review'?`<select name="${f}">${['Needs Review','In Progress','Verified','Issue Flagged'].map(v=>`<option ${v===current[f]?'selected':''}>${v}</option>`).join('')}</select>`:`<input name="${f}" type="${f==='auditDate'?'date':'text'}" value="${esc(current[f])}">`}</label>`).join('')}
function renderAttention(){const ds=stationDevices(current.stationId),cards=[['Location & ownership',current.location&&current.office&&current.department,'Confirm location, facility, and department'],['Device identification',ds.every(d=>d.afpmgTag),`${ds.filter(d=>!d.afpmgTag).length} devices need an asset tag`],['Audit ownership',current.auditor&&current.auditDate,'Auditor and date should be entered']];$('attentionCards').innerHTML=cards.map(([h,good,t])=>`<div class="attention ${good?'good':''}"><b>${good?'✓':'⚠'} ${h}</b><p>${t}</p></div>`).join('')}
function deviceState(d){if(!d.afpmgTag)return['red','Expected device not identified'];const miss=[!d.serialNumber&&'serial',!d.assignedUser&&'user',d.deviceType==='Phone'&&!d.phoneExt&&'extension'].filter(Boolean);return miss.length?['amber','Missing '+miss.join(', ')]:['green','Complete']}
function renderDevices(){const ds=stationDevices(current.stationId);$('deviceCards').innerHTML=ds.map((d,i)=>{const[x,t]=deviceState(d);return`<button class="deviceCard ${x} ${i===currentDevice?'active':''}" onclick="editDevice(${i})"><b>${d.deviceType}</b><div>${esc(d.afpmgTag||'Tag missing')}</div><small>${t}</small></button>`}).join('');$('deviceEditor').innerHTML=currentDevice===null?'':deviceEditor(ds[currentDevice])}
function editDevice(i){currentDevice=i;renderDevices();document.querySelectorAll('[data-df]').forEach(el=>el.oninput=e=>stationDevices(current.stationId)[i][e.target.dataset.df]=e.target.value)}function deviceEditor(d){return`<div class="deviceEditor"><h3>${d.deviceType} details</h3><div class="formGrid">${deviceFields.map(f=>`<label>${labels[f]}<input data-df="${f}" value="${esc(d[f])}"></label>`).join('')}</div></div>`}
function renderChecks(){$('checks').innerHTML=checks.map(f=>`<label><input type="checkbox" data-check="${f}" ${current[f]?'checked':''}> ${f.replace(/([A-Z])/g,' $1')}</label>`).join('');$('auditNotes').value=current.notes||''}
function renderQueueFilters(){const deps=[...new Set(stations.filter(s=>!current.location||s.location===current.location).map(s=>s.department))];$('queueFilters').innerHTML=['All',...deps].map(d=>`<button class="${d===queueDept?'active':''}" onclick="queueDept='${esc(d)}';renderQueueFilters();renderQueue()">${esc(d)}</button>`).join('')}
function queueData(){const q=$('queueSearch').value.toLowerCase();return stations.filter(s=>(!current.location||s.location===current.location)&&(queueDept==='All'||s.department===queueDept)&&(!q||[s.station,s.stationId,s.department].join(' ').toLowerCase().includes(q))&&matchSet('location',s)&&matchSet('office',s)&&matchSet('businessLine',s)&&matchSet('department',s))}
function renderQueue(){const list=queueData(),verified=list.filter(s=>s.review==='Verified').length;$('routeProgress').innerHTML=`<div class="routeBox"><b>${verified}/${list.length} verified</b><div class="bar"><i style="width:${list.length?verified/list.length*100:0}%"></i></div></div>`;$('queueList').innerHTML=list.map(s=>`<button class="qitem ${s.stationId===current.stationId?'current':''}" onclick="switchStation('${s.stationId}')"><small>${s.stationId}</small><b>${esc(s.station)}</b><span>${esc(s.department)} · ${completion(s)}%</span></button>`).join('')}
function switchStation(id){$('audit').close();openAudit(id);$('queuePane').classList.remove('open')}
function showPage(p){document.querySelectorAll('.auditSection').forEach(x=>x.classList.toggle('active',x.dataset.page===p));document.querySelectorAll('.auditNav button').forEach(x=>x.classList.toggle('active',x.dataset.section===p));if(p==='review')renderReview()}
function renderReview(){const fd=new FormData($('stationForm'));const missing=missingList(current);$('reviewBox').innerHTML=`<div class="reviewCard"><h2>${esc(fd.get('station')||current.station)}</h2><p>${esc(fd.get('location')||current.location)} / ${esc(fd.get('office')||current.office)} / ${esc(fd.get('department')||current.department)}</p></div><div class="reviewCard"><b>${missing.length?missing.length+' missing categories':'Essential information complete'}</b><p>${missing.join(', ')||'No essential station categories are missing.'}</p></div>`}
function collect(){const fd=new FormData($('stationForm'));stationFields.forEach(f=>current[f]=fd.get(f));document.querySelectorAll('[data-check]').forEach(c=>current[c.dataset.check]=c.checked);current.notes=$('auditNotes').value;current.devicesMatchedCount=stationDevices(current.stationId).filter(d=>d.afpmgTag).length}
function save(next){collect();const edits=JSON.parse(localStorage.getItem('pmgAuditEdits')||'{}');edits[current.stationId]=current;localStorage.setItem('pmgAuditEdits',JSON.stringify(edits));apply();toast('Station saved locally');if(next)navigate(1);else $('audit').close()}
function navigate(dir){const list=queueData(),i=list.findIndex(s=>s.stationId===current.stationId),n=list[(i+dir+list.length)%list.length];if(n)switchStation(n.stationId)}function quickPass(){current.review='Verified';checks.forEach(c=>current[c]=true);renderAudit();toast('Quick pass applied; save to commit')}function flagIssue(){current.review='Issue Flagged';showPage('verify');$('auditNotes').focus();toast('Station flagged; document the issue')}
function closeAudit(){$('audit').close()}function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({stations,devices},null,2)],{type:'application/json'}));a.download='pmg-inventory-export.json';a.click()}function toast(t){$('toast').textContent=t;$('toast').style.display='block';clearTimeout(window.tt);window.tt=setTimeout(()=>$('toast').style.display='none',2200)}
init();
