const $=id=>document.getElementById(id);let stations=[],devices=[],filtered=[],sortKey='sourceNo',sortDir=1,current=null,currentStep=0,currentDevice=null;const steps=['station','devices','verify','review'];
const fields=['location','office','floor','suite','businessLine','department','station','expectedSlots','review','auditor','auditDate'];
const deviceFields=['afpmgTag','serialNumber','assignedUser','status','manufacturer','model','ipAddress','phoneExt','phoneMac','warrantyStatus','warrantyDate','notes'];
const labels={location:'Location',office:'Facility / Office',floor:'Floor',suite:'Suite',businessLine:'Business Line',department:'Department',station:'Station Name',expectedSlots:'Expected Hardware',review:'Audit Status',auditor:'Auditor',auditDate:'Audit Date',afpmgTag:'AFPMG Tag',serialNumber:'Serial Number',assignedUser:'Assigned User',status:'Device Status',manufacturer:'Manufacturer',model:'Model',ipAddress:'IP Address',phoneExt:'Phone Extension',phoneMac:'Phone MAC',warrantyStatus:'Warranty Status',warrantyDate:'Warranty Date',notes:'Notes'};
async function init(){try{[stations,devices]=await Promise.all([fetch('data/stations.json').then(r=>r.json()),fetch('data/devices.json').then(r=>r.json())]);const saved=JSON.parse(localStorage.getItem('pmgAuditEdits')||'{}');stations=stations.map(s=>({...s,...saved[s.stationId]}));$('loadState').textContent=`${stations.length} stations loaded`;buildFilters();bind();apply()}catch(e){$('loadState').textContent='Data load failed';console.error(e)}}
function options(id,vals,label){$(id).innerHTML=`<option value="">${label}</option>`+[...new Set(vals.filter(Boolean))].sort().map(x=>`<option>${esc(x)}</option>`).join('')}
function buildFilters(){options('location',stations.map(x=>x.location),'All locations');options('office',stations.map(x=>x.office),'All facilities / offices');options('business',stations.map(x=>x.businessLine),'All business lines');options('department',stations.map(x=>x.department),'All departments');options('status',['Needs Review','In Progress','Verified','Issue Flagged'],'All statuses');options('device',[...new Set(devices.map(x=>x.deviceType))],'Any device type');$('queueLocation').innerHTML='<option value="">All locations</option>'+[...new Set(stations.map(x=>x.location))].map(x=>`<option>${x}</option>`).join('')}
function bind(){['search','location','office','business','department','status','device','matched'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',apply));document.querySelectorAll('th[data-sort]').forEach(th=>th.onclick=()=>{const k=th.dataset.sort;sortDir=sortKey===k?-sortDir:1;sortKey=k;apply()});document.querySelectorAll('.auditBody nav button').forEach(b=>b.onclick=()=>showStep(steps.indexOf(b.dataset.step)));$('queueLocation').onchange=renderQueue}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function stationDevices(id){return devices.filter(d=>d.stationId===id)}
function apply(){const q=$('search').value.toLowerCase();filtered=stations.filter(s=>{const ds=stationDevices(s.stationId),text=[...Object.values(s),...ds.flatMap(Object.values)].join(' ').toLowerCase();return(!q||text.includes(q))&&(!$('location').value||s.location===$('location').value)&&(!$('office').value||s.office===$('office').value)&&(!$('business').value||s.businessLine===$('business').value)&&(!$('department').value||s.department===$('department').value)&&(!$('status').value||s.review===$('status').value)&&(!$('device').value||ds.some(d=>d.deviceType===$('device').value))&&(!$('matched').value||($('matched').value==='with'?s.devicesMatchedCount>0:s.devicesMatchedCount===0))});filtered.sort((a,b)=>String(a[sortKey]??'').localeCompare(String(b[sortKey]??''),undefined,{numeric:true})*sortDir);render()}
function render(){const tr=s=>`<tr onclick="openAudit('${s.stationId}')"><td><b>${esc(s.station)}</b></td><td>${esc(s.stationId)}</td><td>${esc(s.location)}</td><td>${esc(s.office)}</td><td>${esc(s.floor)}</td><td>${esc(s.businessLine)}</td><td>${esc(s.department)}</td><td>${s.devicesMatchedCount}/${stationDevices(s.stationId).length}</td><td><span class="pill ${s.review==='In Progress'?'progress':''}">${esc(s.review)}</span></td><td><button onclick="event.stopPropagation();openAudit('${s.stationId}')">Inspect</button></td></tr>`;$('rows').innerHTML=filtered.map(tr).join('');$('cards').innerHTML=filtered.map(s=>`<button class="stationCard" onclick="openAudit('${s.stationId}')"><div class="row"><small>${esc(s.stationId)}</small><span class="pill ${s.review==='In Progress'?'progress':''}">${esc(s.review)}</span></div><h3>${esc(s.station)}</h3><div>${esc(s.location)} · ${esc(s.office)} · ${esc(s.floor||'Floor not listed')}</div><div>${esc(s.businessLine)} · ${esc(s.department)}</div><small>${s.devicesMatchedCount}/${stationDevices(s.stationId).length} devices have matched data</small></button>`).join('');$('resultCount').textContent=`Showing ${filtered.length} of ${stations.length} stations`;$('kStations').textContent=stations.length;$('kDevices').textContent=devices.length;$('kReview').textContent=stations.filter(x=>x.review!=='Verified').length;$('kLocations').textContent=new Set(stations.map(x=>x.location)).size}
function resetFilters(){['search','location','office','business','department','status','device','matched'].forEach(id=>$(id).value='');apply();toast('All filters cleared')}
function openAudit(id){current=stations.find(x=>x.stationId===id)||{stationId:'NEW-'+Date.now(),station:'New Station',review:'Needs Review'};$('auditName').textContent=current.station;$('auditId').textContent=current.stationId;$('auditContext').textContent=[current.location,current.office,current.floor,current.suite,current.department].filter(Boolean).join(' / ');$('stationForm').innerHTML=fields.map(f=>`<label>${labels[f]}${f==='review'?`<select name="${f}">${['Needs Review','In Progress','Verified','Issue Flagged'].map(x=>`<option ${x===current[f]?'selected':''}>${x}</option>`).join('')}</select>`:`<input name="${f}" type="${f==='auditDate'?'date':'text'}" value="${esc(current[f])}">`}</label>`).join('');$('checks').innerHTML=['labelPresent','labelsReplaced','chargersLabeled','printerIpLabeled','phoneExtVerified','phoneMacRecorded','phoneDisplayVerified','devicesAccounted'].map(f=>`<label><input type="checkbox" name="${f}" ${current[f]?'checked':''}> ${f.replace(/([A-Z])/g,' $1')}</label>`).join('');$('auditForm').notes.value=current.notes||'';renderDeviceCards();renderQueue();showStep(0);$('audit').showModal()}
function renderQueue(){const l=$('queueLocation').value,list=stations.filter(s=>!l||s.location===l);$('queueList').innerHTML=list.map(s=>`<button class="qitem ${current&&s.stationId===current.stationId?'current':''}" onclick="openFromQueue('${s.stationId}')"><small>${s.stationId}</small><b>${esc(s.station)}</b><div>${esc(s.location)} · ${esc(s.floor)}</div></button>`).join('')}
function openFromQueue(id){$('audit').close();openAudit(id);$('queue').classList.remove('open')}
function toggleQueue(){$('queue').classList.toggle('open')}
function renderDeviceCards(){const ds=stationDevices(current.stationId);$('deviceCards').innerHTML=ds.map((d,i)=>`<button class="deviceCard ${d.afpmgTag?'has':''} ${currentDevice===i?'active':''}" onclick="editDevice(${i})"><b>${d.deviceType}</b><div>${esc(d.afpmgTag||'Tag missing')}</div><small>${esc(d.status)}</small></button>`).join('');$('deviceEditor').innerHTML=currentDevice===null?'':editorHTML(ds[currentDevice])}
function editorHTML(d){return `<div class="deviceEditor"><h3>${d.deviceType} details</h3><div class="formgrid">${deviceFields.map(f=>`<label>${labels[f]}<input data-device-field="${f}" value="${esc(d[f])}"></label>`).join('')}</div></div>`}
function editDevice(i){currentDevice=i;renderDeviceCards();document.querySelectorAll('[data-device-field]').forEach(el=>el.oninput=e=>stationDevices(current.stationId)[i][e.target.dataset.deviceField]=e.target.value)}
function showStep(i){currentStep=Math.max(0,Math.min(3,i));document.querySelectorAll('.step').forEach(x=>x.classList.toggle('active',x.dataset.pane===steps[currentStep]));document.querySelectorAll('.auditBody nav button').forEach(x=>x.classList.toggle('active',x.dataset.step===steps[currentStep]));$('nextStep').style.display=currentStep===3?'none':'inline-block';$('save').style.display=currentStep===3?'inline-block':'none';if(currentStep===3)review()}
function nextStep(){showStep(currentStep+1)}function previousStep(){showStep(currentStep-1)}
function review(){const fd=new FormData($('auditForm')),missing=['location','office','station','auditor','auditDate'].filter(f=>!fd.get(f));$('reviewBox').innerHTML=`<h2>${esc(fd.get('station'))}</h2><p>${esc(fd.get('location'))} / ${esc(fd.get('office'))} / ${esc(fd.get('floor'))}</p><h3>${missing.length?'Missing: '+missing.map(x=>labels[x]).join(', '):'Essential station fields complete'}</h3><p>${stationDevices(current.stationId).filter(d=>!d.afpmgTag).length} expected devices still need an AFPMG tag.</p>`}
function collect(){const fd=new FormData($('auditForm'));fields.forEach(f=>current[f]=fd.get(f));current.notes=fd.get('notes');['labelPresent','labelsReplaced','chargersLabeled','printerIpLabeled','phoneExtVerified','phoneMacRecorded','phoneDisplayVerified','devicesAccounted'].forEach(f=>current[f]=fd.get(f)==='on');current.devicesMatchedCount=stationDevices(current.stationId).filter(d=>d.afpmgTag).length}
function saveStation(){collect();const i=stations.findIndex(x=>x.stationId===current.stationId);if(i<0)stations.push(current);const edits=JSON.parse(localStorage.getItem('pmgAuditEdits')||'{}');edits[current.stationId]=current;localStorage.setItem('pmgAuditEdits',JSON.stringify(edits));$('audit').close();apply();toast('Station saved locally')}
function saveAndNext(){const id=current.stationId,loc=current.location;saveStation();const route=stations.filter(x=>x.location===loc),i=route.findIndex(x=>x.stationId===id),n=route[(i+1)%route.length];if(n)openAudit(n.stationId)}
function closeAudit(){$('audit').close()}function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({stations,devices},null,2)],{type:'application/json'}));a.download='pmg-inventory-export.json';a.click()}
function toast(t){$('toast').textContent=t;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',2200)}
init();
